### ISSUE TITLE
Upgrade to 11.0 SP9

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/aras-send-to#1] opened 2017-10-02 19:06 UTC
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by AngelaIp** [comment] 2017-10-24 10:05
Surprise! I can confirm that this one still works for 11.0 SP9 in a Windows 7 64bit environment.

**Comment by EliJDonahue** [comment] 2017-10-24 11:59
Awesome! If you’d like to score an easy pull request for Hacktoberfest you can update the history section of the readme with the following changes:

* Remove “Unlike community projects that have been migrated and archived, this project will be updated for compatibility with the latest release of Aras Innovator.”
* Add Aras 11.0 SP9 to the supported versions table for release 9.3.

**Comment by EliJDonahue** [comment] 2017-10-24 15:52
Closing issue since the project has been tested in Aras 11 SP9 and the documentation is updated.

**Closed as completed by EliJDonahue** 2017-10-24 15:52 UTC
